version: '3.9'
services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./resources/seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
